### ISSUE TITLE
Nabla UI fixes

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#385]
## Context
Creating a single ticket for all the Nabla UI bugs listed in the notion ticket

## To-Do

- [x] Input field should only take numeric input, currently takes non-numeric inputs
- [x] Input field takes higher value than available balance, should only take until balance
- [x] Token selection drodown should not repeat token options, if token A is selected in the first dropdown of swap, then only token B and C should be shown in the second dropdown

### Notes
Notion [ticket](https://www.notion.so/satoshipay/Test-the-Nabla-UI-on-portal-510fe67db7f243ab89dbd8debb05cb5b?pvs=4)

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/385?planning-poker) with Zenhub @TorstenStueber

**Comment by TorstenStueber** [comment]
These issues are fixed on the branch `refactor/replace-contract-library`.

Please test and confirm here: https://deploy-preview-326--rococo-souffle-a625f5.netlify.app/pendulum/dashboard

**Comment by prayagd** [comment]
Thanks, Checking

**Comment by TorstenStueber** [comment]
@prayagd can you confirm that it works? Can we close this ticket?

**Comment by prayagd** [comment]
@TorstenStueber Sure
